[package]
name = "madlab"
version = "0.1.2"
edition = "2021"
authors = ["Artur Gwoździowski <gwozdyk@gmain.com>"]
keywords = ["physics", "sandbox", "simulation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.2"
rapier2d = { version = "0.17.2", features = [ "simd-stable" ] }
crossbeam = "0.8.2"

[build-dependencies]
embed-resource = "2.1.1"
